#!/usr/bin/env bash
#DEFAULT="default"
PROFILE=${AWS_PROFILE:-swiftcommercedemo}
BUCKET=demo.swiftcommerce.co
DIR=./dist/
aws  s3  sync $DIR s3://$BUCKET/ --profile "$PROFILE" --region "us-east-1" --acl public-read 
